#!/bin/bash

# Enable the proxy extension in notebook and lab
jupyter serverextension enable --py jupyter_server_proxy
jupyter labextension install @jupyterlab/server-proxy
jupyter lab build

code-server --install-extension ms-python.python
code-server --install-extension yzane.markdown-pdf
code-server --install-extension yzhang.markdown-all-in-one
code-server --install-extension fcrespo82.markdown-table-formatter

# Install the VS code proxy
pip install -e.

# Create work directory and switch into it
mkdir work
export CODE_WORKINGDIR=./work
echo "export CODE_WORKINGDIR=${CODE_WORKINGDIR}"       >> .profile

# Add path to k8s tools
export PATH=$PATH:~/shared/tools
echo "export PATH=$PATH:~/shared/tools"   >> .profile

# Install Azure CLI
pip install azure-cli
